updated storybook to include links and code
GovTechSG/sgds-govtech-react pull request #36
Opened 2020-09-14 06:43 UTC by joetancy

updated the docs as requested

2020-09-14 08:01 UTC, joetancy commented
Have been hitting Insecure Processing of Data in one of the files, please advise! thanks!

2020-09-14 09:02 UTC, joetancy commented
also added notification component

2020-09-23 04:39 UTC, weijunyu requested changes

2020-09-23 04:39 UTC, weijunyu commented on src/components/Notification.js
> +            id="cancel-notification"
`id` attribute can be removed

2020-09-23 04:41 UTC, weijunyu commented
Only 1 fix, otherwise LGTM!

2020-09-23 16:13 UTC, merged