A slightly more configurable footer
GovTechSG/sgds-govtech-react pull request #39
Opened 2020-09-28 11:05 UTC by pivotal-gordon-krull

I have added configuration for `is-fluid` classname to the Footer sections via `isFluid` prop (similar to other components like `Container` and `MainNav`).

Included as well are some quality of life updates:
- Converted `Footer` to a React functional component
- Added PropTypes for existing props
- Added example Fluid Footer to the `Footer` stories in Storybook

2020-09-28 14:08 UTC, weijunyu requested changes

2020-09-28 14:08 UTC, weijunyu commented on src/components/Footer.js
> +  links: PropTypes.objectOf({
This currently throws an error with the examples, I believe the proptype should be `shapeOf` instead

2020-09-28 14:08 UTC, weijunyu commented on src/components/Footer.js
> +  isFluid: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
I think we are only using bool here :)

2020-09-29 00:42 UTC, pivotal-gordon-krull commented on src/components/Footer.js
> +  isFluid: PropTypes.oneOfType([PropTypes.bool, PropTypes.string]),
I have updated to only use bool. I wasn't entirely sure and was using `Container` as a reference here which has both.

2020-09-29 00:42 UTC, pivotal-gordon-krull commented on src/components/Footer.js
> +  links: PropTypes.objectOf({
Fixed.

2020-09-29 10:43 UTC, merged