Sgds 194 Base and Informational Card
GovTechSG/sgds-govtech-react pull request #53
Opened 2022-01-13 10:13 UTC by clukhei

1) Add Cards and sub components
2) Hide props bsPrefix, prop as on Card Wrapper only 
3) Update branch from dev
4) Use SGDSWrapper on Card Wrapper 
5) Add Unit tests of Card
6) Documentation of Card based on Figma

2022-01-13 10:53 UTC, clukhei commented on src/components/Card/Card.tsx
> +        <SGDSWrapper
@haphizi use SGDSWrapper for outermost component, pass in html element type using as prop (by default its a div). can take a look at the SGDSWrapper Function in ThemeProvider.tsx

2022-01-18 07:10 UTC, rav3 requested changes

2022-01-18 07:10 UTC, rav3 commented on stories/Card/Card.stories.mdx
> +          <Card.Title href="#">Card Title</Card.Title>
Duplicate href here. Maybe try to remove it and see if the stretch link work

2022-01-18 07:10 UTC, rav3 commented on stories/Card/Card.stories.mdx
> +    <Card style={{ width: '18rem' }}>
Can remove the inline width here, the card should be able to stretch itself to contain within the grid

2022-01-18 09:03 UTC, haphizi commented on src/components/Card/Card.tsx
> +        <SGDSWrapper
icic, noted thanks!

2022-01-18 23:00 UTC, rav3 approved these changes

2022-01-19 06:58 UTC, merged