Sgds 224
GovTechSG/sgds-govtech-react pull request #54
Opened 2022-01-19 03:45 UTC by haphizi

2022-01-19 03:49 UTC, haphizi commented on stories/Form/FormValidation.stories.mdx
> +import { ArgsTable, Canvas, Meta, Story } from '@storybook/addon-docs';
take a look here LT.

2022-01-19 03:56 UTC, haphizi commented on stories/Form/FormValidation.stories.mdx
> +import { ArgsTable, Canvas, Meta, Story } from '@storybook/addon-docs';
Here the issue is <Form.Control.feedback> by default is placed after <Form.Control>, so it should render the text after the <Form.Control> element upon form validation, but figma styling requires it to be placed before <Form.Control>.

2022-01-19 07:43 UTC, clukhei requested changes
Hihi Pagination is buggy 

1.ellipsis should not appear when page numbers are at the ends. 
![Screenshot 2022-01-19 at 3 19 19 PM](https://user-images.githubusercontent.com/55618945/150085612-109c1398-961b-4380-bfeb-9fc2f18f74cd.png)

2. ellipsis button onclick jumps by 3 but it disables when its at page 7. max page is 10. 
i.e. it cant reach the ends.

2022-01-19 07:43 UTC, clukhei commented on src/components/Form/FormControl.tsx
> +      let component;
Both are returning Component regardless of searchIcon true/false. You can set conditional statement just for icon element, using ternary operator.
this way you wont have to repeat Component code twice 

```jsx
return(
<Component
 {...props}
 type={type}
.../>
{searchIcon ? <span><i /> </span> : null }
)
```

2022-01-19 07:43 UTC, clukhei commented on src/components/Form/FormControl.tsx
> +            <div style={{ display: 'flex' }}>
This form input with icon is still under discussion right? To use form group approach to build this or use stylings @rav3 

don't recommend adding stylings here for neatness and consistency. ideally styling should come from sgds css with a selector that we can use. Thinking about the other frameworks vue, angular will have to match the stylings here as well and things may get messy and hard to maintain when there are alot of stylings coming from diff sources.

2022-01-19 07:43 UTC, clukhei commented on src/components/Paginations/Paginations.tsx
> +  // setItemsPerPage: React.Dispatch<React.SetStateAction<number>>;
can delete commented out code not in use

2022-01-19 07:43 UTC, clukhei commented on src/components/Paginations/Paginations.tsx
> +// import PropTypes from 'prop-types';
How about naming this Pagination under Pagination folder.  Paginations and Pagination may confuse user on which to use and the difference is not very obvious. 

the original bootstrap Pagination can be renamed as PaginationFrame or PaginationUI under Pagination folder.

2022-01-19 07:43 UTC, clukhei commented on src/components/Paginations/Paginations.tsx
> +
the condition directionVariant = 'text' or 'icon' or 'icon-text' only changes the content of direction but not the wrapper <Pagination.Next> or <Pagination.Prev>. Dont include the Pagination.Next  or Pagination.Prev in the condition check, to reduce code duplication 
 e.g
```jsx
const directionContent = () => {
if (directionVariant === 'text') {
  return "Previous" 
}
if (directionVariant === 'text-icon') {
  return <icon...> Previous
}

return <icon>
}
 
<Pagination.Prev ...> {directionContent()}</Pagination.Prev> 
```

2022-01-19 07:43 UTC, clukhei commented on src/components/Paginations/Paginations.tsx
> +  let pageIncrementBtn = null;
this variable is for ellipsis increment , so the variable should be more obvious that its an ellipsis btn 

so instead of pageIncrementBtn can call it ellipsisIncrementBtn

2022-01-19 07:43 UTC, clukhei commented on src/components/Paginations/Paginations.tsx
> +  if (ellipsisOn === false) {
ellipsisOn is a boolean. so can directly use if(!ellipsisOn)

2022-01-20 01:29 UTC, rav3 commented on src/components/Form/FormControl.tsx
> +            <div style={{ display: 'flex' }}>
Agree with using form group for the icon. I'll do up the structure in HTML and CSS

2022-01-20 04:06 UTC, haphizi commented on src/components/Form/FormControl.tsx
> +      let component;
thanks for pointing out

2022-01-20 04:10 UTC, haphizi commented on src/components/Form/FormControl.tsx
> +            <div style={{ display: 'flex' }}>
so in that case, i will leave it as it is first.

2022-01-20 04:11 UTC, haphizi commented on src/components/Paginations/Paginations.tsx
> +  // setItemsPerPage: React.Dispatch<React.SetStateAction<number>>;
noted

2022-01-20 04:13 UTC, haphizi commented on src/components/Paginations/Paginations.tsx
> +// import PropTypes from 'prop-types';
hmm, i will rename it as PaginationBase perhaps

2022-01-20 07:23 UTC, rav3 commented on src/components/Form/FormControl.tsx
> +            <div style={{ display: 'flex' }}>
Created 2 variants for them left and right. 
Both CSS styling are embedded into the sgds.css

Code example here
https://codepen.io/rav3tey/pen/RwLmJNm

2022-01-26 03:15 UTC, rav3 approved these changes

2022-01-26 03:21 UTC, clukhei approved these changes

2022-01-26 03:24 UTC, merged